version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login --no-include-email --region us-east-1
      - REPOSITORY_URI=686773406557.dkr.ecr.us-east-1.amazonaws.com/first
      - GCODEBUILD_GIT_BRANCH=`git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }'`
      - echo $GCODEBUILD_GIT_BRANCH
      - pwd
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - echo $GIT_PUB
      - echo $GIT_PUB | base64 -d > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - git clone git@github.com:pagevamp/dev-guide.git


  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ecs-101 .
      - echo $GCODEBUILD_GIT_BRANCH
      - docker tag ecs-101:latest $REPOSITORY_URI:$GCODEBUILD_GIT_BRANCH
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - eval $(aws ecr get-login --no-include-email | sed 's|https://||')
      - docker push $REPOSITORY_URI:$GCODEBUILD_GIT_BRANCH
      - printf '[{"name":"custom","imageUri":"%s"}]' $REPOSITORY_URI:$GCODEBUILD_GIT_BRANCH > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
